# Generated by Django 4.2.1 on 2023-05-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_number', models.IntegerField()),
                ('text', models.TextField()),
                ('answer', models.TextField()),
                ('photos', models.TextField(blank=True)),
                ('files', models.TextField(blank=True)),
                ('time_median', models.FloatField(blank=True, default=0)),
                ('category', models.TextField()),
            ],
        ),
    ]
