# Generated by Django 4.2.1 on 2023-05-09 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_number', models.IntegerField()),
                ('text', models.TextField()),
                ('answer', models.TextField()),
                ('photos', models.TextField(blank=True)),
                ('files', models.TextField(blank=True)),
                ('time_median', models.FloatField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolveGiaApp.category')),
            ],
        ),
    ]
