# Generated by Django 4.2.1 on 2023-05-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SolveGiaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='category',
        ),
    ]
