# Generated by Django 4.2.1 on 2023-05-24 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SolveGiaApp', '0002_remove_task_category_remove_variant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SolveGiaApp.category'),
        ),
        migrations.AddField(
            model_name='variant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SolveGiaApp.category'),
        ),
    ]
