# Generated by Django 4.2.1 on 2023-06-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolveGiaApp', '0002_homework_tries_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcu',
            name='group_hws',
            field=models.ManyToManyField(blank=True, to='SolveGiaApp.variant'),
        ),
    ]
