# Generated by Django 4.2.1 on 2023-05-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolveGiaApp', '0003_task_category_variant_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_median',
        ),
        migrations.AddField(
            model_name='task',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='KindaTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voices', models.ManyToManyField(blank=True, to='SolveGiaApp.kindauser')),
            ],
        ),
    ]
