# Generated by Django 4.2.1 on 2023-05-24 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SolveGiaApp', '0004_kindauser_remove_task_time_median_task_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='voices',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='KindaTask',
        ),
        migrations.DeleteModel(
            name='KindaUser',
        ),
    ]
