# Generated by Django 4.2.1 on 2023-05-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolveGiaApp', '0005_task_voices_delete_kindatask_delete_kindauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_type_number',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
